import 'package:conference_hall_booking/source/common_packages_export.dart';

double screenWidth = 0.0;
double screenHeight = 0.0;
const String testUrl = 'http://10.0.7.159:8000/api/';
// const String testUrl = 'http://192.168.1.16:8000/api/';
const String liveUrl = 'http://10.0.7.159:8000/api/';
String? finalEmail;
String? finalToken;
List<BookingData> listOfBookings = [];
List<ConferenceHallData> listOfConferenceHall = [];
List<LocationData> listOfLocations = [];
List<CurrentUserData> listOfCurrentUserData = [];
List<BookingData> listOfMyMeetings = [];
List<BookingData> listOfMyOldMeetings = [];
List<BookingData> listOfTodayMeetings = [];
List<BookingData> listOfOtherMeetings = [];
CurrentUserData? currentUserData;
late Future<BookingDetails> bookingDetailsResponse;
late Future<ConferenceHallDetails> conferenceHallDetailsResponse;
late Future<LocationDetails> locationDetailsResponse;
// late Future<CurrentUserData> currentUserDataResponse;
bool isSearched = false;
List<BookingData> listOfFoundBookingsFromAllMeetings = [];
List<BookingData> listOfFoundBookingsFromMyMeetings = [];
List<BookingData> listOfFoundBookingsFromMyOldMeetings = [];
List<BookingData> listOfFoundBookingFromTodayMeetings = [];
List<BookingData> listOfFoundBookingsFromOtherMeetings = [];
BookingData toBeUpdatedBookingData = BookingData();
BookingData toBeAddedBookingData = BookingData();
